# Generated by Django 2.0.2 on 2018-02-20 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='order',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='node',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='main.Page'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'node')},
        ),
    ]
